config/routes.rb
Rails.application.routes.draw do 
  
  devise_for :users
  devise_scope :user do
    get 'users/thanks' => 'users/registrations#thanks'
  end

  root to: "posts#top"
  resources :posts do 
    resources :comments, only: [:create,:new]
    collection do
      get "search"
      get "top"
      get "like"
    end
  end

  resources :users, only: [:edit, :update,:show] do
    collection do 
      get "follow"
      get "follower"
    end
  end


  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  
  resources :relationships, only: [:create, :destroy] do 
    collection do 
      get "rank"
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="main__good__like-link" id="like-link-<%= post.id %>">
  <% if user_signed_in? %>
    <% if current_user.likes.find_by(post_id: post.id) %>
      <%= link_to unlike_path(post.id), method: :delete, remote: true do %>
          <div class = "iine__button">❤️<%= post.likes.count %></div>
      <% end %>
    <% else %>
      <%= link_to like_path(post.id), method: :post, remote: true do %>
          <div class = "iine__button">♡️<%= post.likes.count %></div>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to like_path(post.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= post.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post )) %>');