config/routes.rb
Rails.application.routes.draw do 
  
  devise_for :users
  devise_scope :user do
    get 'users/thanks' => 'users/registrations#thanks'
  end

  root to: "posts#top"
  resources :posts do 
    resources :comments, only: [:create,:new]
    collection do
      get "search"
      get "top"
      get "like"
    end
  end

  resources :users, only: [:edit, :update,:show] do
    collection do 
      get "follow"
      get "follower"
    end
  end


  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
  
  resources :relationships, only: [:create, :destroy] do 
    collection do 
      get "rank"
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :image, presence: true
  mount_uploader :image, ImageUploader

  def self.search(search)
    if search
      Post.where("team LIKE(?)", "%#{search}%")
    else
      Post.all
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :move_to_index, except: [:index, :show, :search, :top]
  

  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(3)
  end

  def top 
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).last(3).reverse
  end

  def edit    
    @post = Post.find(params[:id])
  end

  def update
     post = Post.find(params[:id])
     post.update(post_params)
     redirect_to posts_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def search
    @posts = Post.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(3)
  end

  def like
    @posts = Post.all.order("likes_count desc").limit(3)
  end

  private
    def post_params
      params.require(:post).permit(:text,:image,:team).merge(user_id: current_user.id)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.main__searchform
  = form_with(url: search_posts_path, local: true,method: :get) do |f|
    = f.text_field :keyword, placeholder: "チーム検索"
    = f.submit "検索"

app/views/posts/_header.html.haml
- if user_signed_in?
  .header
    .header__logo
      = link_to "/posts" do
        BaseballWear
    .header__profile
      .header__profile__image
        - if current_user.image.present?
          = image_tag current_user.image.to_s, size: "55x55"
        - else
          = image_tag "noimage.jpg",size: "55x55"
      .header__profile__team
        - if current_user.favorite_team == "ジャイアンツ"
          = link_to "/posts/search?utf8=✓&keyword=ジャイアンツ&commit=検索" do
            = "ジャイアンツ"
        - elsif current_user.favorite_team == "ベイスターズ"
          = link_to "/posts/search?utf8=✓&keyword=ベイスターズ&commit=検索" do
            = "ベイスターズ"
        - elsif current_user.favorite_team == "タイガース"
          = link_to "/posts/search?utf8=✓&keyword=タイガース&commit=検索" do
            = "タイガース"
        - elsif current_user.favorite_team == "カープ"
          = link_to "/posts/search?utf8=✓&keyword=カープ&commit=検索" do
            = "カープ"
        - elsif current_user.favorite_team == "ドラゴンズ"
          = link_to "/posts/search?utf8=✓&keyword=ドラゴンズ&commit=検索" do
            = "ドラゴンズ"
        - elsif current_user.favorite_team == "スワローズ"
          = link_to "/posts/search?utf8=✓&keyword=スワローズ&commit=検索" do
            = "スワローズ"
        - elsif current_user.favorite_team == "ライオンズ"
          = link_to "/posts/search?utf8=✓&keyword=ライオンズ&commit=検索" do
            = "ライオンズ"
        - elsif current_user.favorite_team == "ホークス"
          = link_to "/posts/search?utf8=✓&keyword=ホークス&commit=検索" do
            = "ホークス"
        - elsif current_user.favorite_team == "イーグルス"
          = link_to "/posts/search?utf8=✓&keyword=イーグルス&commit=検索" do
            = "イーグルス"
        - elsif current_user.favorite_team == "マリーンズ"
          = link_to "/posts/search?utf8=✓&keyword=マリーンズ&commit=検索" do
            = "マリーンズ"
        - elsif current_user.favorite_team == "ファイターズ"
          = link_to "/posts/search?utf8=✓&keyword=ファイターズ&commit=検索" do
            = "ファイターズ"
        - elsif current_user.favorite_team == "バファローズ"
          = link_to "/posts/search?utf8=✓&keyword=バファローズ&commit=検索" do
            = "バファローズ"
      .header__profile__name
        = link_to user_path(current_user) do
          = current_user.nickname
      .header__profile__following
        = link_to follow_users_path(current_user) do
          フォロー 
          = current_user.followings.count
      .header__profile__followed
        = link_to follow_users_path(current_user) do
          フォロワー
          = current_user.followers.count
      .header__profile__rank
        = link_to rank_relationships_path do
          ユーザーランキング
      .header__profile__popular
        = link_to like_posts_path do
          投稿ランキング
    .header__link
      .header__link__edit
        = link_to edit_user_path(current_user) do
          ユーザー編集
      .header__link__post
        = link_to new_post_path do
          投稿
- else
  .header
    .header__logo
      = link_to "/posts" do
        BaseballWear
    .header__link
      .header__link__login
        = link_to new_user_session_path do
          ログイン
      .header__link__registration
        = link_to new_user_registration_path do
          登録

app/views/posts/_like.html.haml
- if Like.find_by(user_id: current_user.id,post_id: @post.id)
  = link_to "/posts/#{post.id}/likes", method: :delete
  %i.material-icons star
- else
  = link_to "/posts/#{post.id}/likes", method: :post
  %i.material-icons star_border
= post.likes.length

app/views/posts/_posts.html.erb
<%= render 'likes/like', post: post %>

app/views/posts/edit.html.haml
= render partial: "header"


.post
  .post__top
    Post
  .post__form
    = form_for @post do |f|
      %label{class: "post__form__image"}
        image
        = f.file_field :image, class: "post__form__blank"
        
      
      %label{class: "post__form__team"}
        team 
        = f.select :team, ["","ジャイアンツ","ベイスターズ","タイガース","カープ","ドラゴンズ","スワローズ","ライオンズ","ホークス","イーグルス","マリーンズ","ファイターズ","バファローズ"]
       
      
      %label{class: "post__form__text"}
        text
        = f.text_area :text, class: "post__form__blank"
        

        = f.submit "send" 

app/views/posts/index.html.haml
= render partial: "header"

.main
  
  = render partial: "form"
  
  .main__text
    Newposts
  .main__good  
    = render partial: 'posts/posts', collection: @posts, as: :post, id: :good_function   
  .main__post
    %ul.main__post__box
      - if @posts
        - @posts.each do |post|
          %li.main__post__box__image
            = image_tag post.image.to_s, size: "350x500"
            %ul.main__post__box__image__text
              .main__post__box__image__text__2
                %li チーム名
                = post.team
                %li 投稿時間
                = post.created_at
                %li 投稿者
                = post.user.nickname
                %li
                = link_to "Detail", "/posts/#{post.id}"
    .main__post__page
    = paginate(@posts)
  
    

app/views/posts/like.html.haml
= render partial: "header"

.main
  
  = render partial: "form"
  
  .main__text
    Popularposts
  
  .main__post
    %ul.main__post__box
      - if @posts
        - @posts.each.with_index(1) do |post,i|
          %li.main__post__box__image
            = image_tag post.image.to_s, size: "350x500"
            %ul.main__post__box__image__text
              .main__post__box__image__text__2
                = i 
                位
                %li 
                ♡
                = post.likes_count
                %li チーム名
                = post.team
                %li 投稿時間
                = post.created_at
                %li 投稿者
                = post.user.nickname
                %li
                = link_to "Detail", "/posts/#{post.id}"

app/views/posts/new.html.haml
= render partial: "header"

.post
  .post__top
    Post
  .post__form
    = form_for @post do |f|
      
      %label{class: "post__form__image"}
        image
        = f.file_field :image, class: "post__form__blank"
        
      
      %label{class: "post__form__team"}
        team 
        = f.select :team, ["","ジャイアンツ","ベイスターズ","タイガース","カープ","ドラゴンズ","スワローズ","ライオンズ","ホークス","イーグルス","マリーンズ","ファイターズ","バファローズ"]
       
      
      %label{class: "post__form__text"}
        text
        = f.text_area :text, class: "post__form__blank"
        

      = f.submit "send" 

    

app/views/posts/search.html.haml
= render partial: "header"

= render partial: "form"




.main__post
  .main__good
    = render partial: 'posts/posts', collection: @posts, as: :post
  %ul.main__post__box
    - if @posts
      - @posts.each do |post|
        %li.main__post__box__image
          = image_tag post.image.to_s, size: "350x500"
          %ul.main__post__box__image__text
            .main__post__box__image__text__2
              %li チーム名
              = post.team
              %li 投稿時間
              = post.created_at
              = link_to "Detail", "/posts/#{post.id}"
  .main__post__page
  = paginate(@posts)

app/views/posts/show.html.haml
= render partial: "header"

.main
  = render partial: "form"
  
  - if user_signed_in? && current_user.id == @post.user_id 
    .main__manuplate
      = link_to "/posts/#{@post.id}",method: :delete do
        削除
      = link_to "/posts/#{@post.id}/edit" do
        編集 
  = render partial: 'posts/posts', collection: @posts, as: :post
  .main__content

    .main__content__image
      %p= image_tag @post.image.to_s,size: :"550x600"
      
    .main__content__text
      %pチーム名
      = link_to "/posts/search?utf8=✓&keyword=#{@post.team}&commit=検索" do
        = @post.team
      %pテキスト
      = @post.text
      %p投稿者名
      = link_to @post.user.nickname, "/users/#{@post.user_id}",class: "username"
      = render 'relationships/follow_button', user: @post.user
      %pオンラインショップサイト
      - if @post.team == "ジャイアンツ"
        =link_to "ジャイアンツ公式サイト", "https://store.giants.jp/store/"
      - elsif @post.team == "ベイスターズ"
        =link_to "ベイスターズ公式サイト", "https://ec.baystars.co.jp/"
      - elsif @post.team == "タイガース"
        =link_to "タイガース公式サイト", "https://shop.hanshintigers.jp/"
      - elsif @post.team == "カープ"
        =link_to "カープ公式サイト", "https://www.shop.carp.co.jp/"
      - elsif @post.team == "ドラゴンズ"
        =link_to "ドラゴンズ公式サイト", "https://dragonsshop.info/"
      - elsif @post.team == "スワローズ"
        =link_to "スワローズ公式サイト", "https://shop.yakult-swallows.co.jp/"
      - elsif @post.team == "ライオンズ"
        =link_to "ライオンズ公式サイト", "https://store.seibulions.jp/"
      - elsif @post.team == "ホークス"
        =link_to "ホークス公式サイト", "https://www.softbankhawksstore.jp/"
      - elsif @post.team == "イーグルス"
        =link_to "イーグルス公式サイト", "https://www.rakuten.ne.jp/gold/rakuteneagles/"
      - elsif @post.team == "マリーンズ"
        =link_to "マリーンズ公式サイト", "https://www.marines.co.jp/goods/index.html"
      - elsif @post.team == "ファイターズ"
        =link_to "ファイターズ公式サイト", "https://shop.fighters.co.jp/shopping/"
      - elsif @post.team == "バファローズ"
        =link_to "バファローズ公式サイト", "https://shop.buffaloes.co.jp/"
      
      %pコメント一覧
      - if @comments
        - @comments.each do |c| 
          .comment_style 
            = c.text
          = link_to c.user.nickname, "/users/#{c.user_id}",class: "username"
         
    .main__content__comment
      -if current_user
        = form_with(model: [@post,@comment],url: post_comments_path(@post.id), id: "new_comment") do |f|
          = f.text_field :text, placeholder: "コメント投稿",class: "message-field__area"
          = f.submit "Send"
      - else 
        %p コメント投稿にはログインが必要です

app/views/posts/top.html.haml
.topmain
  .topmain__image
    .topmain__image__text
      Always With Favorite Team
    .topmain__image__link
      = link_to new_user_session_path do
        Login
      =  link_to new_user_registration_path do
        Signup
      = link_to posts_path do
        Only View
    